MODEL_LIST = {
    'AlexNet': ['pytorch'],
    'VGG-11': ['pytorch'],
    'VGG-13': ['pytorch'],
    'VGG-16': ['pytorch', 'tensorflow'],
    'VGG-19': ['pytorch', 'tensorflow'],
    'VGG-11-bn': ['pytorch'],
    'VGG-13-bn': ['pytorch'],
    'VGG-16-bn': ['pytorch'],
    'VGG-19-bn': ['pytorch'],
    'ResNet-18': ['pytorch'],
    'ResNet-34': ['pytorch'],
    'ResNet-50': ['pytorch', 'tensorflow'],
    'ResNet-101': ['pytorch', 'tensorflow'],
    'ResNet-152': ['pytorch', 'tensorflow'],
    'ResNet-50-v2': ['tensorflow'],
    'ResNet-101-v2': ['tensorflow'],
    'ResNet-152-v2': ['tensorflow'],
    'SqueezeNet-1.0': ['pytorch'],
    'SqueezeNet-1.1': ['pytorch'],
    'Densenet-121': ['pytorch', 'tensorflow'],
    'Densenet-169': ['pytorch', 'tensorflow'],
    'Densenet-201': ['pytorch', 'tensorflow'],
    'Densenet-161': ['pytorch'],
    'Inception-v3': ['pytorch', 'tensorflow'],
    'Inception-ResNet-v2': ['tensorflow'],
    'Xception': ['tensorflow'],
    'GoogleNet': ['pytorch'],
    'ShuffleNet': ['pytorch'],
    'MobileNet': ['tensorflow'],
    'MobileNet-v2': ['pytorch', 'tensorflow'],
    'ResNeXt-50-32x4d': ['pytorch'],
    'ResNeXt-101-32x8d': ['pytorch'],
    'Wide-ResNet-50-2': ['pytorch'],
    'Wide-ResNet-101-2': ['pytorch'],
    'NASNet-mobile': ['tensorflow'],
    'NASNet-large': ['tensorflow'],
    'MNASNet-1.0': ['pytorch'],
    'EfficientNet-B0': ['tensorflow'],
    'EfficientNet-B1': ['tensorflow'],
    'EfficientNet-B2': ['tensorflow'],
    'EfficientNet-B3': ['tensorflow'],
    'EfficientNet-B4': ['tensorflow'],
    'EfficientNet-B5': ['tensorflow'],
    'EfficientNet-B6': ['tensorflow'],
    'EfficientNet-B7': ['tensorflow'],
}